name: Android Build

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Super-Linter
        uses: github/super-linter@v4.6.1
        
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v2.2.0
        with:
          java-version: 1.8
          
      - name: Build with Gradle
        run: ./gradlew build
      
      - name: Run Tests
        run: ./gradlew test
        
      - name: Upload a Build Artifact (APK)
        uses: actions/upload-artifact@v2.2.4
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
